import { useEffect, useState, useCallback } from "react";
import { FiSearch, FiCode, FiGitCommit, FiLayers, FiFileText, FiGithub, FiCopy, FiExternalLink, FiX, FiTerminal } from "react-icons/fi";
import toast from "react-hot-toast";

const CommandPalette = ({ isOpen, onClose, username = "kilicdev" }) => {
  const [query, setQuery] = useState("");
  const [selectedIndex, setSelectedIndex] = useState(0);

  const commands = [
    {
      id: "commits",
      title: "View Recent Commits",
      subtitle: "Inspect latest git commits telemetry",
      icon: FiGitCommit,
      category: "Navigation",
      action: () => {
        const el = document.getElementById("commits");
        if (el) el.scrollIntoView({ behavior: "smooth" });
      },
    },
    {
      id: "repos",
      title: "Explore Repositories",
      subtitle: "Browse open-source projects and packages",
      icon: FiCode,
      category: "Navigation",
      action: () => {
        const el = document.getElementById("repos");
        if (el) el.scrollIntoView({ behavior: "smooth" });
      },
    },
    {
      id: "techstack",
      title: "Architecture & Tech Stack",
      subtitle: "Core technologies, languages and frameworks",
      icon: FiLayers,
      category: "Navigation",
      action: () => {
        const el = document.getElementById("techstack");
        if (el) el.scrollIntoView({ behavior: "smooth" });
      },
    },
    {
      id: "readme",
      title: "README Visual Telemetry",
      subtitle: "View live SVG dashboard generated by GitHub Actions",
      icon: FiFileText,
      category: "Navigation",
      action: () => {
        const el = document.getElementById("readme");
        if (el) el.scrollIntoView({ behavior: "smooth" });
      },
    },
    {
      id: "github",
      title: "Open GitHub Profile",
      subtitle: `https://github.com/${username}`,
      icon: FiGithub,
      category: "External",
      action: () => {
        window.open(`https://github.com/${username}`, "_blank");
      },
    },
    {
      id: "copy-url",
      title: "Copy Profile URL",
      subtitle: "Copy kilicdev.com link to clipboard",
      icon: FiCopy,
      category: "Actions",
      action: () => {
        navigator.clipboard.writeText("https://kilicdev.com");
        toast.success("Profile URL copied to clipboard!", {
          style: { background: "#0f172a", color: "#38bdf8" },
        });
      },
    },
    {
      id: "seo-indexer",
      title: "View SEO Indexer Repository",
      subtitle: "Multi-engine SEO indexing CLI tool",
      icon: FiExternalLink,
      category: "Projects",
      action: () => {
        window.open("https://github.com/kilicdev/seo-indexer", "_blank");
      },
    },
  ];

  const filteredCommands = commands.filter(
    (c) =>
      c.title.toLowerCase().includes(query.toLowerCase()) ||
      c.subtitle.toLowerCase().includes(query.toLowerCase()) ||
      c.category.toLowerCase().includes(query.toLowerCase())
  );

  const executeCommand = useCallback(
    (cmd) => {
      cmd.action();
      onClose();
      setQuery("");
    },
    [onClose]
  );

  useEffect(() => {
    setSelectedIndex(0);
  }, [query]);

  useEffect(() => {
    const handleKeyDown = (e) => {
      if ((e.metaKey || e.ctrlKey) && e.key === "k") {
        e.preventDefault();
        if (isOpen) {
          onClose();
        }
      }

      if (!isOpen) return;

      if (e.key === "Escape") {
        onClose();
      } else if (e.key === "ArrowDown") {
        e.preventDefault();
        setSelectedIndex((prev) => (prev + 1) % (filteredCommands.length || 1));
      } else if (e.key === "ArrowUp") {
        e.preventDefault();
        setSelectedIndex((prev) => (prev - 1 + filteredCommands.length) % (filteredCommands.length || 1));
      } else if (e.key === "Enter" && filteredCommands[selectedIndex]) {
        e.preventDefault();
        executeCommand(filteredCommands[selectedIndex]);
      }
    };

    window.addEventListener("keydown", handleKeyDown);
    return () => window.removeEventListener("keydown", handleKeyDown);
  }, [isOpen, onClose, filteredCommands, selectedIndex, executeCommand]);

  if (!isOpen) return null;

  return (
    <div
      className="fixed inset-0 z-50 flex items-start justify-center pt-12 sm:pt-20 px-3 sm:px-4 bg-black/75 backdrop-blur-md animate-fadeIn cursor-pointer"
      onClick={onClose}
    >
      <div
        className="w-full max-w-2xl bg-[#0d0f1c] border border-cyan-500/30 rounded-2xl shadow-[0_0_50px_rgba(6,182,212,0.15)] overflow-hidden flex flex-col cursor-default"
        onClick={(e) => e.stopPropagation()}
      >
        <div className="flex items-center px-3.5 sm:px-4 py-3 sm:py-3.5 border-b border-slate-800/80 gap-2 sm:gap-3">
          <FiSearch className="w-4 sm:w-5 h-4 sm:h-5 text-cyan-400" />
          <input
            type="text"
            value={query}
            onChange={(e) => setQuery(e.target.value)}
            placeholder="Type a command or search..."
            className="flex-1 bg-transparent text-slate-100 placeholder-slate-500 font-sans text-xs sm:text-sm focus:outline-none"
            autoFocus
          />
          <span className="text-[10px] font-mono px-2 py-0.5 rounded bg-slate-800 text-slate-400 border border-slate-700 hidden sm:inline">
            ESC
          </span>
          <button onClick={onClose} className="p-1 text-slate-400 hover:text-slate-200">
            <FiX className="w-5 h-5" />
          </button>
        </div>

        <div className="max-h-80 sm:max-h-96 overflow-y-auto p-2 space-y-1 custom-scrollbar">
          {filteredCommands.length === 0 ? (
            <div className="p-8 text-center text-slate-500 text-xs sm:text-sm font-mono flex flex-col items-center gap-2">
              <FiTerminal className="w-6 h-6 text-slate-600" />
              <span>No commands matching "{query}"</span>
            </div>
          ) : (
            filteredCommands.map((cmd, idx) => {
              const Icon = cmd.icon;
              const isSelected = idx === selectedIndex;
              return (
                <button
                  key={cmd.id}
                  onClick={() => executeCommand(cmd)}
                  onMouseEnter={() => setSelectedIndex(idx)}
                  className={`w-full flex items-center gap-3 px-3 py-2.5 sm:py-3 rounded-xl text-left transition-all duration-150 ${
                    isSelected
                      ? "bg-gradient-to-r from-cyan-950/80 to-purple-950/40 border border-cyan-500/30 text-slate-100"
                      : "text-slate-300 hover:bg-slate-800/40 border border-transparent"
                  }`}
                >
                  <div
                    className={`p-2 rounded-lg ${
                      isSelected
                        ? "bg-cyan-500/20 text-cyan-300"
                        : "bg-slate-800/80 text-slate-400"
                    }`}
                  >
                    <Icon className="w-4 h-4" />
                  </div>
                  <div className="flex-1 min-w-0">
                    <div className="text-xs sm:text-sm font-semibold flex items-center gap-2">
                      <span className="truncate">{cmd.title}</span>
                      <span className="text-[9px] sm:text-[10px] font-mono px-1.5 py-0.2 rounded bg-slate-800 text-slate-400 border border-slate-700/60 shrink-0">
                        {cmd.category}
                      </span>
                    </div>
                    <div className="text-[11px] sm:text-xs text-slate-400 font-mono truncate">
                      {cmd.subtitle}
                    </div>
                  </div>
                  {isSelected && (
                    <span className="text-[10px] sm:text-xs font-mono text-cyan-400 opacity-80 hidden sm:inline">
                      ↵ select
                    </span>
                  )}
                </button>
              );
            })
          )}
        </div>

        <div className="px-4 py-2.5 bg-slate-950/80 border-t border-slate-800/60 flex items-center justify-between text-[10px] sm:text-[11px] font-mono text-slate-400">
          <div className="flex items-center gap-3">
            <span>
              <kbd className="px-1.5 py-0.5 rounded bg-slate-800 border border-slate-700 text-slate-300">↑↓</kbd> navigate
            </span>
            <span>
              <kbd className="px-1.5 py-0.5 rounded bg-slate-800 border border-slate-700 text-slate-300">↵</kbd> select
            </span>
          </div>
          <span className="text-cyan-400/80">kilicdev telemetry</span>
        </div>
      </div>
    </div>
  );
};

export default CommandPalette;
