import { useEffect } from "react";
import { FiX, FiDownload, FiExternalLink, FiMaximize2 } from "react-icons/fi";

const ImageLightbox = ({ isOpen, onClose, src, alt }) => {
  useEffect(() => {
    const handleKeyDown = (e) => {
      if (e.key === "Escape") onClose();
    };
    if (isOpen) {
      window.addEventListener("keydown", handleKeyDown);
    }
    return () => window.removeEventListener("keydown", handleKeyDown);
  }, [isOpen, onClose]);

  if (!isOpen) return null;

  return (
    <div
      className="fixed inset-0 z-50 flex items-center justify-center p-4 sm:p-8 bg-black/85 backdrop-blur-lg animate-fadeIn"
      onClick={onClose}
    >
      <div
        className="relative max-w-5xl w-full bg-[#0d0f1c] border border-cyan-500/30 rounded-2xl p-4 sm:p-6 shadow-[0_0_80px_rgba(6,182,212,0.2)] flex flex-col gap-4 overflow-hidden"
        onClick={(e) => e.stopPropagation()}
      >
        <div className="flex items-center justify-between pb-3 border-b border-slate-800">
          <div className="flex items-center gap-2 text-cyan-400 font-mono text-xs">
            <FiMaximize2 className="w-4 h-4" />
            <span>GitHub Telemetry Visual Inspector</span>
          </div>
          <div className="flex items-center gap-2">
            <a
              href={src}
              target="_blank"
              rel="noreferrer"
              className="p-2 rounded-lg bg-slate-800 text-slate-300 hover:text-cyan-300 hover:bg-slate-700 transition-colors text-xs font-mono flex items-center gap-1.5"
            >
              <FiExternalLink className="w-3.5 h-3.5" />
              <span className="hidden sm:inline">Raw SVG</span>
            </a>
            <a
              href={src}
              download="readme-stats.svg"
              className="p-2 rounded-lg bg-cyan-950/60 border border-cyan-500/40 text-cyan-300 hover:bg-cyan-900/60 transition-colors text-xs font-mono flex items-center gap-1.5"
            >
              <FiDownload className="w-3.5 h-3.5" />
              <span className="hidden sm:inline">Download</span>
            </a>
            <button
              onClick={onClose}
              className="p-2 rounded-lg bg-slate-800 text-slate-400 hover:text-slate-100 transition-colors"
            >
              <FiX className="w-5 h-5" />
            </button>
          </div>
        </div>

        <div className="relative w-full max-h-[75vh] overflow-auto flex items-center justify-center p-2 rounded-xl bg-slate-950 border border-slate-800/80 custom-scrollbar">
          <img src={src} alt={alt || "Telemetry SVG preview"} className="max-w-full h-auto object-contain rounded-lg" />
        </div>

        <div className="flex items-center justify-between text-xs font-mono text-slate-400 pt-1">
          <span>Auto-generated by GitHub Actions workflow</span>
          <span className="text-cyan-400">kilicdev telemetry engine</span>
        </div>
      </div>
    </div>
  );
};

export default ImageLightbox;
